# 应用配置
[app]
name = "数据处理器"
version = "1.0.0"
batch_size = 10
interval_seconds = 30

# 日志配置
[logging]
level = "info"
format = "text"

# 可选的数据库配置（展示配置系统的灵活性）
[database]
host = "localhost"
port = 5432
name = "data_processor"
user = "processor"
password = "secret"
max_connections = 5